# generated by datamodel-codegen:
#   filename:  protocol.json

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated, Any, Literal

from msgspec import UNSET, Meta, UnsetType, field

from pymalloy._protocol.base import Record


class Annotation(Record):
    value: str


class AtomicTypeWithBooleanType(Record, tag_field="kind", tag="boolean_type"):
    pass


class AtomicTypeWithJSONType(Record, tag_field="kind", tag="json_type"):
    pass


class AtomicTypeWithSQLNativeType(Record, tag_field="kind", tag="sql_native_type"):
    sql_type: str | UnsetType = UNSET


class AtomicTypeWithStringType(Record, tag_field="kind", tag="string_type"):
    pass


class CellWithBooleanCell(Record, tag_field="kind", tag="boolean_cell"):
    boolean_value: bool


class CellWithDateCell(Record, tag_field="kind", tag="date_cell"):
    date_value: str


class CellWithJSONCell(Record, tag_field="kind", tag="json_cell"):
    json_value: str


class CellWithNullCell(Record, tag_field="kind", tag="null_cell"):
    pass


class CellWithSQLNativeCell(Record, tag_field="kind", tag="sql_native_cell"):
    sql_native_value: str


class CellWithStringCell(Record, tag_field="kind", tag="string_cell"):
    string_value: str


class CellWithTimestampCell(Record, tag_field="kind", tag="timestamp_cell"):
    timestamp_value: str


class Completion(Record):
    text: str
    type: str


class Help(Record):
    token: str | None
    type: str


class CompilerFailure(Record, tag_field="kind", tag="failure"):
    message: str


class CompilerReady(Record, tag_field="kind", tag="ready"):
    pass


type DateTimeframe = Literal["year", "quarter", "month", "week", "day"]


type DocumentKind = Literal["model", "notebook"]


class FilterableTypeWithBooleanType(Record, tag_field="kind", tag="boolean_type"):
    pass


class FilterableTypeWithDateType(Record, tag_field="kind", tag="date_type"):
    timeframe: DateTimeframe | UnsetType = UNSET


class FilterableTypeWithStringType(Record, tag_field="kind", tag="string_type"):
    pass


class LiteralValueWithBooleanLiteral(Record, tag_field="kind", tag="boolean_literal"):
    boolean_value: bool


class LiteralValueWithDateLiteral(Record, tag_field="kind", tag="date_literal"):
    date_value: str
    granularity: DateTimeframe | UnsetType = UNSET
    timezone: str | UnsetType = UNSET


class LiteralValueWithFilterExpressionLiteral(
    Record, tag_field="kind", tag="filter_expression_literal"
):
    filter_expression_value: str


class LiteralValueWithNullLiteral(Record, tag_field="kind", tag="null_literal"):
    pass


class LiteralValueWithNumberLiteral(Record, tag_field="kind", tag="number_literal"):
    number_value: float
    string_value: str | UnsetType = UNSET


class LiteralValueWithStringLiteral(Record, tag_field="kind", tag="string_literal"):
    string_value: str


class MarkdownCell(Record, tag_field="kind", tag="markdown"):
    text: str


class ModelSource(Record):
    document_kind: DocumentKind = field(name="documentKind")
    imports: Mapping[str, str]
    text: str
    url: str


class NotebookBinding(Record):
    kind: str
    name: str
    source: str


class NotebookInput(Record):
    name: str
    rows: Annotated[int, Meta(ge=0)]


type NumberSubtype = Literal["integer", "decimal", "bigint"]


type OrderByDirection = Literal["asc", "desc"]


class ParameterTypeWithBooleanType(Record, tag_field="kind", tag="boolean_type"):
    pass


class ParameterTypeWithDateType(Record, tag_field="kind", tag="date_type"):
    timeframe: DateTimeframe | UnsetType = UNSET


class ParameterTypeWithJSONType(Record, tag_field="kind", tag="json_type"):
    pass


class ParameterTypeWithNumberType(Record, tag_field="kind", tag="number_type"):
    subtype: NumberSubtype | UnsetType = UNSET


class ParameterTypeWithSQLNativeType(Record, tag_field="kind", tag="sql_native_type"):
    sql_type: str | UnsetType = UNSET


class ParameterTypeWithStringType(Record, tag_field="kind", tag="string_type"):
    pass


class Position(Record):
    character: float
    line: float


class QueryCell(Record, tag_field="kind", tag="query"):
    name: str
    sql: str


class QueryReady(Record, tag_field="kind", tag="query"):
    name: str
    sql: str
    line: float | UnsetType = UNSET


class Range(Record):
    end: Position
    start: Position


type Relationship = Literal["one", "many", "cross"]


class RoutedAnnotation(Record):
    """
    Native annotation routes and payloads alongside the untouched stable annotation.
    """

    content: str
    route: str | None
    text: str


class SQLSchemaNeed(Record, tag_field="kind", tag="sql"):
    connection: str
    key: str
    sql: str


class ScalarField(Record, tag_field="kind", tag="field"):
    path: Sequence[str]


class ScalarGiven(Record, tag_field="kind", tag="given"):
    name: str


class ScalarLiteral(Record, tag_field="kind", tag="literal"):
    type: Literal["string", "number", "boolean", "null", "date", "timestamp"]
    value: str


class ScalarRaw(Record, tag_field="kind", tag="raw"):
    code: str


class SourcePosition(Record):
    character: Annotated[int, Meta(ge=0)]
    line: Annotated[int, Meta(ge=0)]


class SourceRange(Record):
    end: SourcePosition
    start: SourcePosition


class SourceReady(Record, tag_field="kind", tag="source"):
    source: ModelSource


class SourceSpan(Record):
    end: Annotated[int, Meta(ge=0)]
    start: Annotated[int, Meta(ge=0)]


class SymbolInfo(Record):
    children: Sequence[SymbolInfo]
    lens_range: SourceRange = field(name="lensRange")
    name: str
    range: SourceRange
    type: str


type SyntaxOperationKind = Annotated[
    Literal[
        "source",
        "query",
        "block",
        "extend",
        "pipe",
        "ref",
        "sql",
        "dimension",
        "measure",
        "view",
        "nest",
        "group_by",
        "select",
        "aggregate",
        "where",
        "having",
        "limit",
        "primary_key",
        "order_by",
        "asc",
        "desc",
    ],
    Meta(
        description="Constructor structure identified by Malloy's parser, independently of spelling."
    ),
]


class TableSchemaNeed(Record, tag_field="kind", tag="table"):
    connection: str
    key: str
    table_path: str = field(name="tablePath")


class TableSyntax(Record, tag_field="type", tag="table"):
    """
    A native table source, retaining its exact spelling and resolved reference.
    """

    connection: str
    path: str
    source: str


type TimestampTimeframe = Literal[
    "year", "quarter", "month", "week", "day", "hour", "minute", "second"
]


class ViewOperationWithLimit(Record, tag_field="kind", tag="limit"):
    limit: float


class AnnotatedObject(Record):
    annotations: Sequence[RoutedAnnotation]
    kind: str
    path: Sequence[str]


class AtomicTypeWithDateType(Record, tag_field="kind", tag="date_type"):
    timeframe: DateTimeframe | UnsetType = UNSET


class AtomicTypeWithNumberType(Record, tag_field="kind", tag="number_type"):
    subtype: NumberSubtype | UnsetType = UNSET


class AtomicTypeWithTimestampType(Record, tag_field="kind", tag="timestamp_type"):
    timeframe: TimestampTimeframe | UnsetType = UNSET


class AtomicTypeWithTimestamptzType(Record, tag_field="kind", tag="timestamptz_type"):
    timeframe: TimestampTimeframe | UnsetType = UNSET


class CellWithNumberCell(Record, tag_field="kind", tag="number_cell"):
    number_value: float
    string_value: str | UnsetType = UNSET
    subtype: NumberSubtype | UnsetType = UNSET


class Table(Record):
    connection: str
    path: str
    range: SourceRange


type DocumentCell = MarkdownCell | QueryCell


class DocumentReady(Record, tag_field="kind", tag="document"):
    cells: Sequence[DocumentCell]


class FilterableTypeWithNumberType(Record, tag_field="kind", tag="number_type"):
    subtype: NumberSubtype | UnsetType = UNSET


class FilterableTypeWithTimestampType(Record, tag_field="kind", tag="timestamp_type"):
    timeframe: TimestampTimeframe | UnsetType = UNSET


class FilterableTypeWithTimestamptzType(
    Record, tag_field="kind", tag="timestamptz_type"
):
    timeframe: TimestampTimeframe | UnsetType = UNSET


class LiteralValueWithTimestampLiteral(
    Record, tag_field="kind", tag="timestamp_literal"
):
    timestamp_value: str
    granularity: TimestampTimeframe | UnsetType = UNSET
    timezone: str | UnsetType = UNSET


class Location(Record):
    range: Range
    url: str


class NotebookInfo(Record):
    annotations: Sequence[str]
    bindings: Sequence[NotebookBinding]
    execution: Literal["browser", "python", "result"] | None
    inputs: Sequence[NotebookInput]
    kind: str
    message: str | None
    references: Sequence[str]
    source: str


class ParameterTypeWithTimestampType(Record, tag_field="kind", tag="timestamp_type"):
    timeframe: TimestampTimeframe | UnsetType = UNSET


class ParameterTypeWithTimestamptzType(
    Record, tag_field="kind", tag="timestamptz_type"
):
    timeframe: TimestampTimeframe | UnsetType = UNSET


type SchemaNeed = Annotated[TableSchemaNeed | SQLSchemaNeed, Meta(title="SchemaNeed")]


class SourceLocation(Record):
    range: SourceRange
    url: str


class SyntaxOperation(Record):
    arguments: Sequence[str]
    kind: SyntaxOperationKind


class AnnotationInfo(Record):
    content: str
    location: SourceLocation
    route: str
    text: str


class Diagnostic(Record):
    code: str
    data: Any
    error_tag: str | None = field(name="errorTag")
    location: SourceLocation | None
    message: str
    replacement: str | None
    severity: Literal["error", "warning", "debug"]


type FilterableType = (
    FilterableTypeWithStringType
    | FilterableTypeWithBooleanType
    | FilterableTypeWithNumberType
    | FilterableTypeWithDateType
    | FilterableTypeWithTimestampType
    | FilterableTypeWithTimestamptzType
)


class FormatReady(Record, tag_field="kind", tag="format"):
    diagnostics: Sequence[Diagnostic]
    source: str


class GivenInfo(Record):
    annotations: Sequence[AnnotationInfo]
    default_text: str | None = field(name="defaultText")
    location: SourceLocation | None
    name: str
    required: bool
    type: str


class ImportInfo(Record):
    location: SourceLocation
    url: str


class Reference1(Record):
    annotations: Sequence[AnnotationInfo]
    default_text: str | None = field(name="defaultText")
    definition_location: SourceLocation | None = field(name="definitionLocation")
    definition_type: str = field(name="definitionType")
    kind: str
    location: SourceLocation
    text: str


type LiteralValue = (
    LiteralValueWithStringLiteral
    | LiteralValueWithNumberLiteral
    | LiteralValueWithDateLiteral
    | LiteralValueWithTimestampLiteral
    | LiteralValueWithBooleanLiteral
    | LiteralValueWithNullLiteral
    | LiteralValueWithFilterExpressionLiteral
)


class Needs(Record):
    schemas: Sequence[SchemaNeed]
    urls: Sequence[str]


class ParameterTypeWithFilterExpressionType(
    Record, tag_field="kind", tag="filter_expression_type"
):
    filter_type: FilterableType


class ParameterValue(Record):
    name: str
    value: LiteralValue


class ParsedImport(Record):
    """
    The compiler-selected string literal, including delimiters, in Unicode codepoints.
    """

    location: SourceLocation
    reference: SourceSpan
    url: str


class QueryArrowSourceWithSourceReference(
    Record, tag_field="kind", tag="source_reference"
):
    name: str
    parameters: Sequence[ParameterValue] | UnsetType = UNSET
    path: Sequence[str] | UnsetType = UNSET


class QueryDefinitionWithQueryReference(
    Record, tag_field="kind", tag="query_reference"
):
    name: str
    parameters: Sequence[ParameterValue] | UnsetType = UNSET
    path: Sequence[str] | UnsetType = UNSET


class QueryDescriptor(Record):
    """
    A query available on a compiled model.

    name identifies the selection accepted by Model.query, including zero-based run:N and sql:N names for unnamed document queries.

    kind distinguishes an authored run, named query, source view or SQL document cell using the values "run", "named", "view" and "sql".

    location supplies an authored URL and range when available, otherwise null. Python positions use zero-based lines and Unicode code-point character offsets.
    """

    kind: Literal["run", "named", "view", "sql"]
    location: SourceLocation | None
    name: str


class Reference(Record):
    name: str
    parameters: Sequence[ParameterValue] | UnsetType = UNSET
    path: Sequence[str] | UnsetType = UNSET


class ViewDefinitionWithViewReference(Record, tag_field="kind", tag="view_reference"):
    name: str
    parameters: Sequence[ParameterValue] | UnsetType = UNSET
    path: Sequence[str] | UnsetType = UNSET


class ViewOperationWithOrderBy(Record, tag_field="kind", tag="order_by"):
    field_reference: Reference
    direction: OrderByDirection | UnsetType = UNSET


class CompileError(Record, tag_field="kind", tag="error"):
    diagnostics: Sequence[Diagnostic]
    message: str


class CompileNeeds(Record, tag_field="kind", tag="needs"):
    needs: Needs


class ExpressionWithFieldReference(Record, tag_field="kind", tag="field_reference"):
    name: str
    parameters: Sequence[ParameterValue] | UnsetType = UNSET
    path: Sequence[str] | UnsetType = UNSET


class ExpressionWithLiteralValue(Record, tag_field="kind", tag="literal_value"):
    literal_value: LiteralValue


class ExpressionWithMovingAverage(Record, tag_field="kind", tag="moving_average"):
    field_reference: Reference
    partition_fields: Sequence[Reference] | UnsetType = UNSET
    rows_following: float | UnsetType = UNSET
    rows_preceding: float | UnsetType = UNSET


class ExpressionWithTimeTruncation(Record, tag_field="kind", tag="time_truncation"):
    field_reference: Reference
    truncation: TimestampTimeframe


class ModelReady(Record, tag_field="kind", tag="model"):
    compiler_version: str = field(name="compilerVersion")
    queries: Sequence[QueryDescriptor]
    source: ModelSource


class ParseReport(Record):
    compiler_version: str = field(name="compilerVersion")
    completions: Sequence[Completion]
    diagnostics: Sequence[Diagnostic]
    help: Help | None
    imports: Sequence[ParsedImport]
    symbols: Sequence[SymbolInfo]
    tables: Sequence[Table]
    url: str


class ParseReady(Record, tag_field="kind", tag="parse"):
    report: ParseReport


type Model = Records


class AnonymousQueryInfo(Record):
    schema: Schema
    annotations: Sequence[Annotation] | UnsetType = UNSET
    code: str | UnsetType = UNSET
    definition: Query | UnsetType = UNSET
    location: Location | UnsetType = UNSET


type AtomicType = (
    AtomicTypeWithStringType
    | AtomicTypeWithBooleanType
    | AtomicTypeWithNumberType
    | AtomicTypeWithJSONType
    | AtomicTypeWithSQLNativeType
    | AtomicTypeWithDateType
    | AtomicTypeWithTimestampType
    | AtomicTypeWithArrayType
    | AtomicTypeWithRecordType
    | AtomicTypeWithTimestamptzType
)


class AtomicTypeWithArrayType(Record, tag_field="kind", tag="array_type"):
    element_type: AtomicType


class AtomicTypeWithRecordType(Record, tag_field="kind", tag="record_type"):
    fields: Sequence[DimensionInfo]


type Cell = (
    CellWithStringCell
    | CellWithBooleanCell
    | CellWithDateCell
    | CellWithTimestampCell
    | CellWithNumberCell
    | CellWithJSONCell
    | CellWithRecordCell
    | CellWithArrayCell
    | CellWithNullCell
    | CellWithSQLNativeCell
)


class CellWithArrayCell(Record, tag_field="kind", tag="array_cell"):
    array_value: Sequence[Cell]


class CellWithRecordCell(Record, tag_field="kind", tag="record_cell"):
    record_value: Sequence[Cell]


class CheckReady(Record, tag_field="kind", tag="check"):
    report: CheckReport


class CheckReport(Record):
    compiler_version: str = field(name="compilerVersion")
    completions: Sequence[Completion]
    diagnostics: Sequence[Diagnostic]
    help: Help | None
    imports: Sequence[ParsedImport]
    model: NativeMetadata
    ok: bool
    queries: Sequence[QueryDescriptor]
    symbols: Sequence[SymbolInfo]
    tables: Sequence[Table]
    url: str


class ConcreteSyntax(Record, tag_field="type", tag="syntax"):
    kind: Literal[
        "document", "source", "query", "field", "expression", "annotation", "clause"
    ]
    name: str | None
    operation: SyntaxOperation | None
    parts: Sequence[str | SyntaxNode]


type Data = DataWithRecordCell | DataWithArrayCell


class DataWithArrayCell(Record, tag_field="kind", tag="array_cell"):
    array_value: Sequence[Cell]


class DataWithRecordCell(Record, tag_field="kind", tag="record_cell"):
    record_value: Sequence[Cell]


class DimensionInfo(Record):
    name: str
    type: AtomicType
    annotations: Sequence[Annotation] | UnsetType = UNSET


type Expression = (
    ExpressionWithFieldReference
    | ExpressionWithTimeTruncation
    | ExpressionWithFilteredField
    | ExpressionWithLiteralValue
    | ExpressionWithMovingAverage
)


class ExpressionWithFilteredField(Record, tag_field="kind", tag="filtered_field"):
    field_reference: Reference
    where: Sequence[FilterOperation]


class Field(Record):
    expression: Expression
    annotations: Sequence[Annotation] | UnsetType = UNSET


type FieldInfo = (
    FieldInfoWithDimension
    | FieldInfoWithMeasure
    | FieldInfoWithJoin
    | FieldInfoWithView
    | FieldInfoWithCalculate
)


class FieldInfoWithCalculate(Record, tag_field="kind", tag="calculate"):
    name: str
    type: AtomicType
    annotations: Sequence[Annotation] | UnsetType = UNSET


class FieldInfoWithDimension(Record, tag_field="kind", tag="dimension"):
    name: str
    type: AtomicType
    annotations: Sequence[Annotation] | UnsetType = UNSET


class FieldInfoWithJoin(Record, tag_field="kind", tag="join"):
    name: str
    relationship: Relationship
    schema: Schema
    annotations: Sequence[Annotation] | UnsetType = UNSET


class FieldInfoWithMeasure(Record, tag_field="kind", tag="measure"):
    name: str
    type: AtomicType
    annotations: Sequence[Annotation] | UnsetType = UNSET


class FieldInfoWithView(Record, tag_field="kind", tag="view"):
    name: str
    schema: Schema
    annotations: Sequence[Annotation] | UnsetType = UNSET
    definition: View | UnsetType = UNSET


type Filter = FilterWithFilterString | FilterWithLiteralEquality


class FilterOperation(Record):
    filter: Filter


class FilterWithFilterString(Record, tag_field="kind", tag="filter_string"):
    expression: Expression
    filter: str


class FilterWithLiteralEquality(Record, tag_field="kind", tag="literal_equality"):
    expression: Expression
    value: LiteralValue


class Inspection(Record):
    annotations: Sequence[AnnotationInfo]
    dependencies: Sequence[str]
    diagnostics: Sequence[Diagnostic]
    givens: Sequence[GivenInfo]
    imports: Sequence[ImportInfo]
    model: NativeMetadata
    model_annotations: Sequence[AnnotationInfo] = field(name="modelAnnotations")
    queries: Sequence[QueryDescriptor]
    import_: ImportInfo | None | UnsetType = field(name="import", default=UNSET)
    reference: Reference1 | None | UnsetType = UNSET


class InspectionReady(Record, tag_field="kind", tag="inspection"):
    inspection: Inspection


type ModelEntryValue = ModelEntryValueWithSource | ModelEntryValueWithQuery


class ModelEntryValueWithQuery(Record, tag_field="kind", tag="query"):
    name: str
    schema: Schema
    annotations: Sequence[Annotation] | UnsetType = UNSET
    code: str | UnsetType = UNSET
    definition: Query | UnsetType = UNSET
    location: Location | UnsetType = UNSET


class ModelEntryValueWithSource(Record, tag_field="kind", tag="source"):
    name: str
    schema: Schema
    annotations: Sequence[Annotation] | UnsetType = UNSET
    parameters: Sequence[ParameterInfo] | UnsetType = UNSET


class ModelInfo(Record):
    anonymous_queries: Sequence[AnonymousQueryInfo]
    entries: Sequence[ModelEntryValue]
    annotations: Sequence[Annotation] | UnsetType = UNSET


class NativeMetadata(Record):
    annotations: Sequence[AnnotatedObject]
    model: ModelInfo | None
    sources: Sequence[SourceInfo]


class ParameterInfo(Record):
    name: str
    type: ParameterType
    default_value: LiteralValue | UnsetType = UNSET


type ParameterType = (
    ParameterTypeWithStringType
    | ParameterTypeWithBooleanType
    | ParameterTypeWithNumberType
    | ParameterTypeWithJSONType
    | ParameterTypeWithSQLNativeType
    | ParameterTypeWithDateType
    | ParameterTypeWithTimestampType
    | ParameterTypeWithArrayType
    | ParameterTypeWithRecordType
    | ParameterTypeWithFilterExpressionType
    | ParameterTypeWithTimestamptzType
)


class ParameterTypeWithArrayType(Record, tag_field="kind", tag="array_type"):
    element_type: AtomicType


class ParameterTypeWithRecordType(Record, tag_field="kind", tag="record_type"):
    fields: Sequence[DimensionInfo]


class Query(Record):
    definition: QueryDefinition
    annotations: Sequence[Annotation] | UnsetType = UNSET


type QueryArrowSource = (
    QueryArrowSourceWithRefinement | QueryArrowSourceWithSourceReference
)


class QueryArrowSourceWithRefinement(Record, tag_field="kind", tag="refinement"):
    base: QueryDefinition
    refinement: ViewDefinition


type QueryDefinition = (
    QueryDefinitionWithArrow
    | QueryDefinitionWithQueryReference
    | QueryDefinitionWithRefinement
)


class QueryDefinitionWithArrow(Record, tag_field="kind", tag="arrow"):
    source: QueryArrowSource
    view: ViewDefinition


class QueryDefinitionWithRefinement(Record, tag_field="kind", tag="refinement"):
    base: QueryDefinition
    refinement: ViewDefinition


class Records(Record):
    check: CheckReport
    diagnostic: Diagnostic
    inspection: Inspection
    notebook: NotebookInfo
    query: QueryDescriptor
    response: Response
    state: State


type Response = (
    CompilerReady
    | CompileNeeds
    | CompileError
    | CompilerFailure
    | ModelReady
    | QueryReady
    | DocumentReady
    | InspectionReady
    | SourceReady
    | CheckReady
    | ParseReady
    | FormatReady
    | SyntaxReady
)


class Result(Record):
    connection_name: str
    schema: Schema
    annotations: Sequence[Annotation] | UnsetType = UNSET
    data: Data | UnsetType = UNSET
    model_annotations: Sequence[Annotation] | UnsetType = UNSET
    query_timezone: str | UnsetType = UNSET
    source_annotations: Sequence[Annotation] | UnsetType = UNSET
    sql: str | UnsetType = UNSET


type Scalar = Annotated[
    ScalarField
    | ScalarGiven
    | ScalarLiteral
    | ScalarUnary
    | ScalarBinary
    | ScalarCall
    | ScalarCast
    | ScalarNullTest
    | ScalarTruncate
    | ScalarFilter
    | ScalarCase
    | ScalarRaw,
    Meta(
        description="Symbolic scalar syntax; Malloy remains responsible for typing and semantics."
    ),
]


class ScalarBinary(Record, tag_field="kind", tag="binary"):
    left: Scalar
    operator: str
    right: Scalar


class ScalarCall(Record, tag_field="kind", tag="call"):
    args: Sequence[Scalar]
    name: str
    receiver: Sequence[str] | None


class Branch(Record):
    then: Scalar
    when: Scalar


class ScalarCase(Record, tag_field="kind", tag="case"):
    branches: Sequence[Branch]
    otherwise: Scalar


class ScalarCast(Record, tag_field="kind", tag="cast"):
    safe: bool
    type: str
    value: Scalar


class ScalarFilter(Record, tag_field="kind", tag="filter"):
    predicate: Scalar
    value: Scalar


class ScalarNullTest(Record, tag_field="kind", tag="null_test"):
    negated: bool
    value: Scalar


class ScalarSyntax(Record, tag_field="type", tag="scalar"):
    """
    A scalar operation tree paired with its original authored spelling.
    """

    scalar: Scalar
    source: str


class ScalarTruncate(Record, tag_field="kind", tag="truncate"):
    unit: str
    value: Scalar


class ScalarUnary(Record, tag_field="kind", tag="unary"):
    operator: Literal["-", "not"]
    value: Scalar


class Schema(Record):
    fields: Sequence[FieldInfo]


class SourceInfo(Record):
    name: str
    schema: Schema
    annotations: Sequence[Annotation] | UnsetType = UNSET
    parameters: Sequence[ParameterInfo] | UnsetType = UNSET


class State(Record):
    diagnostics: Sequence[Diagnostic]
    error: str | None
    inspection: Inspection | None
    queries: Sequence[QueryDescriptor]
    result: Result | None
    revision: Annotated[int, Meta(ge=0)]
    status: Literal["idle", "loading", "ready", "error", "closed"]


type SyntaxNode = Annotated[
    ConcreteSyntax | ScalarSyntax | TableSyntax,
    Meta(
        description="Lossless authored syntax. Strings retain all syntax outside editable bindings."
    ),
]


class SyntaxReady(Record, tag_field="kind", tag="syntax"):
    syntax: SyntaxNode


class View(Record):
    definition: ViewDefinition
    annotations: Sequence[Annotation] | UnsetType = UNSET


type ViewDefinition = (
    ViewDefinitionWithArrow
    | ViewDefinitionWithViewReference
    | ViewDefinitionWithRefinement
    | ViewDefinitionWithSegment
)


class ViewDefinitionWithArrow(Record, tag_field="kind", tag="arrow"):
    source: ViewDefinition
    view: ViewDefinition


class ViewDefinitionWithRefinement(Record, tag_field="kind", tag="refinement"):
    base: ViewDefinition
    refinement: ViewDefinition


class ViewDefinitionWithSegment(Record, tag_field="kind", tag="segment"):
    operations: Sequence[ViewOperation]


type ViewOperation = (
    ViewOperationWithGroupBy
    | ViewOperationWithAggregate
    | ViewOperationWithOrderBy
    | ViewOperationWithLimit
    | ViewOperationWithWhere
    | ViewOperationWithNest
    | ViewOperationWithHaving
    | ViewOperationWithDrill
    | ViewOperationWithCalculate
)


class ViewOperationWithAggregate(Record, tag_field="kind", tag="aggregate"):
    field_: Field = field(name="field")
    name: str | UnsetType = UNSET


class ViewOperationWithCalculate(Record, tag_field="kind", tag="calculate"):
    field_: Field = field(name="field")
    name: str


class ViewOperationWithDrill(Record, tag_field="kind", tag="drill"):
    filter: Filter


class ViewOperationWithGroupBy(Record, tag_field="kind", tag="group_by"):
    field_: Field = field(name="field")
    name: str | UnsetType = UNSET


class ViewOperationWithHaving(Record, tag_field="kind", tag="having"):
    filter: Filter


class ViewOperationWithNest(Record, tag_field="kind", tag="nest"):
    view: View
    name: str | UnsetType = UNSET


class ViewOperationWithWhere(Record, tag_field="kind", tag="where"):
    filter: Filter
