"""Compose, verify, and edit a Malloy model through a Python roundtrip."""

from pathlib import Path
from tempfile import TemporaryDirectory

import pymalloy as pm

orders = (
    pm.sql(
        "SELECT * FROM (VALUES (1, 40, 'North'), (2, 2, 'North')) t(id, amount, region)"
    )
    .extend(
        pm.primary_key("id"),
        pm.measure(revenue=pm.col("amount").sum().doc("Gross order revenue in USD.")),
        pm.view(
            by_region=pm.query(
                pm.group_by(pm.col("region")),
                pm.aggregate(pm.col("revenue")),
                pm.order_by(pm.col("revenue").desc(), pm.col("region")),
            ).doc("Revenue by region with stable ranking.")
        ),
    )
    .doc("One row per order, with amounts in USD.")
)
candidate = pm.draft().define(orders=orders)
report = candidate.validate(
    {
        "unique_order_id": pm.ref("orders").pipe(
            pm.query(
                pm.group_by(pm.col("id")),
                pm.aggregate(n=pm.count()),
                pm.having(pm.col("n") > 1),
            )
        ),
        "non_null_order_id": pm.ref("orders").pipe(
            pm.query(pm.where(pm.col("id").is_null()), pm.select(pm.col("id")))
        ),
        "known_total": pm.ref("orders").pipe(
            pm.query(
                pm.aggregate(pm.col("revenue")), pm.having(pm.col("revenue") != 42)
            )
        ),
    }
)
with TemporaryDirectory() as directory:
    path = report.save(Path(directory) / "orders.malloy", warnings_as_errors=True)
    loaded = pm.read_model(path)
    namespace = {}
    # Execute constructor calls generated by PyMalloy, with Malloy text quoted as data.
    exec(loaded.to_python(name="restored"), namespace)  # noqa: S102
    restored = namespace["restored"]
    assert restored["orders"]["revenue"].equals(loaded["orders"]["revenue"])
    updated = restored.define(
        orders=restored["orders"].extend(
            pm.measure(average_order=pm.col("amount").avg().doc("Mean order USD."))
        )
    )
    assert "average_order" not in loaded["orders"].names
    model = updated.compile()
    try:
        assert model.query("orders.by_region").preview().rows() == [
            {"region": "North", "revenue": 42}
        ]
        print(model.query("orders.by_region").preview().rows())
    finally:
        model.close()
