"""Typed language reports generated from the compiler contract."""

from pymalloy._protocol.codec import to_dict
from pymalloy._protocol.records import (
    AnnotatedObject,
    AnnotationInfo,
    CheckReport,
    Diagnostic,
    DocumentCell,
    GivenInfo,
    ImportInfo,
    Inspection,
    MarkdownCell,
    NativeMetadata,
    ParsedImport,
    ParseReport,
    QueryCell,
    QueryDescriptor,
    RoutedAnnotation,
    SourceLocation,
    SourcePosition,
    SourceRange,
    SourceSpan,
    SymbolInfo,
)

__all__ = [
    "AnnotatedObject",
    "AnnotationInfo",
    "CheckReport",
    "Diagnostic",
    "DocumentCell",
    "GivenInfo",
    "ImportInfo",
    "Inspection",
    "MarkdownCell",
    "NativeMetadata",
    "ParseReport",
    "ParsedImport",
    "QueryCell",
    "QueryDescriptor",
    "RoutedAnnotation",
    "SourceLocation",
    "SourcePosition",
    "SourceRange",
    "SourceSpan",
    "SymbolInfo",
    "to_dict",
]
